name: Publish Design System

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsup.config.ts'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Run tests
      run: npm test
      
    - name: Bump version
      id: bump-version
      run: |
        # Bump patch version
        npm version patch --no-git-tag-version
        echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
    - name: Publish to GitHub Packages
      run: |
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.bump-version.outputs.version }}
        release_name: Release v${{ steps.bump-version.outputs.version }}
        body: |
          ## Changes in v${{ steps.bump-version.outputs.version }}
          
          - Updated components
          - Bug fixes and improvements
          
          ## Installation
          ```bash
          npm install @d-via/design-system@${{ steps.bump-version.outputs.version }}
          ```
        draft: false
        prerelease: false
        
    - name: Notify d-via-final
      uses: actions/github-script@v6
      with:
        script: |
          // Déclencher le workflow de mise à jour dans d-via-final
          await github.rest.actions.createWorkflowDispatch({
            owner: 'votre-username',
            repo: 'd-via-final',
            workflow_id: 'update-design-system.yml',
            ref: 'main'
          });
