name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '18'
  NPM_VERSION: '8'

jobs:
  # Job de validation et tests
  test:
    name: Tests et Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm run install:all
        
    - name: Lint code
      run: npm run lint
      
    - name: Type check
      run: |
        cd design-system-dvia && npm run type-check
        cd ../d-via-final && npx tsc --noEmit
        
    - name: Run tests
      run: npm run test
      continue-on-error: true

  # Job de build du design system
  build-design-system:
    name: Build Design System
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm run install:all
        
    - name: Build design system
      run: npm run build:design-system
      
    - name: Upload design system artifacts
      uses: actions/upload-artifact@v4
      with:
        name: design-system-dist
        path: design-system-dvia/dist/
        retention-days: 7

  # Job de build de l'application Next.js
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [test, build-design-system]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm run install:all
        
    - name: Download design system artifacts
      uses: actions/download-artifact@v4
      with:
        name: design-system-dist
        path: design-system-dvia/dist/
        
    - name: Build frontend
      run: npm run build:frontend
      
    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: d-via-final/.next/
        retention-days: 7

  # Job de déploiement (seulement sur main)
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [build-design-system, build-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npm run install:all
        
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: design-system-dist
        path: design-system-dvia/dist/
        
    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: d-via-final/.next/
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./d-via-final
        vercel-args: '--prod'

  # Job de notification
  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
    - name: Notify Success
      if: needs.deploy.result == 'success'
      run: |
        echo "✅ Déploiement réussi sur Vercel"
        
    - name: Notify Failure
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ Échec du déploiement sur Vercel"